//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : TransportSystem
//  @ File Name : IrregularCustomer.cs
//  @ Date : 12/17/2013
//  @ Author : khoatd
//
//


namespace AppCommon.Entity
{
    public class IrregularCustomer
    {
    }
}
