//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : TransportSystem
//  @ File Name : RegularCustomer.cs
//  @ Date : 12/17/2013
//  @ Author : khoatd
//
//


/// <summary>
/// The Entity namespace.
/// </summary>
namespace AppCommon.Entity
{
    /// <summary>
    /// Class RegularCustomer.
    /// </summary>
    public class RegularCustomer
    {
        /// <summary>
        /// The id
        /// </summary>
        private string _id;

        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <quantity>The identifier.</quantity>
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }
        /// <summary>
        /// The _name
        /// </summary>
        private string _name;

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <quantity>The name.</quantity>
        public string name
        {
            get { return _name; }
            set { _name = value; }
        }
        /// <summary>
        /// The _phone_number
        /// </summary>
        private string _phone_number;

        /// <summary>
        /// Gets or sets the phone_number.
        /// </summary>
        /// <quantity>The phone_number.</quantity>
        public string phone_number
        {
            get { return _phone_number; }
            set { _phone_number = value; }
        }
        /// <summary>
        /// The _id_card_number
        /// </summary>
        private string _id_card_number;

        /// <summary>
        /// Gets or sets the id_card_number.
        /// </summary>
        /// <quantity>The id_card_number.</quantity>
        public string id_card_number
        {
            get { return _id_card_number; }
            set { _id_card_number = value; }
        }
        /// <summary>
        /// The _address
        /// </summary>
        private string _address;

        /// <summary>
        /// Gets or sets the address.
        /// </summary>
        /// <quantity>The address.</quantity>
        public string address
        {
            get { return _address; }
            set { _address = value; }
        }
    }
}
