//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public string id { get; set; }
        public string object_id { get; set; }
        public string object_type { get; set; }
        public string action { get; set; }
        public System.DateTime date_time { get; set; }
        public string user_id { get; set; }
    }
}
