//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public string id { get; set; }
        public string name { get; set; }
        public int seat_count { get; set; }
        public int sub_seat_count { get; set; }
        public int bed_count { get; set; }
        public int sub_bed_count { get; set; }
    }
}
