//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string id { get; set; }
        public string name { get; set; }
        public string company { get; set; }
        public string id_card_number { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
    }
}
