//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishedTour
    {
        public string id { get; set; }
        public int total_tickets { get; set; }
        public decimal total_amount { get; set; }
        public string bus_id { get; set; }
        public string tour_id { get; set; }
        public Nullable<System.DateTime> finished_date { get; set; }
        public string description { get; set; }
    }
}
