//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuaranteeFeeConfiguration
    {
        public string id { get; set; }
        public decimal value_from { get; set; }
        public decimal value_to { get; set; }
        public decimal guarantee_fee { get; set; }
    }
}
