//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistoryDetail
    {
        public string id { get; set; }
        public string parent_id { get; set; }
        public string property_name { get; set; }
        public string old_value { get; set; }
        public string new_value { get; set; }
    }
}
