//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSaleDate
    {
        public string id { get; set; }
        public int ticket_sale_day { get; set; }
        public int ticket_sale_month { get; set; }
        public int ticket_sale_year { get; set; }
        public int before_days { get; set; }
    }
}
