//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketReturnFeeConfiguration
    {
        public string id { get; set; }
        public int before_day { get; set; }
        public int before_hour { get; set; }
        public int fee_percent { get; set; }
        public decimal fee_amount { get; set; }
    }
}
