//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstToDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThanhVanTranSysEntities : DbContext
    {
        public ThanhVanTranSysEntities()
            : base("name=ThanhVanTranSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditTrail> AuditTrails { get; set; }
        public virtual DbSet<AuditTrailDetail> AuditTrailDetails { get; set; }
        public virtual DbSet<Bus> Buses { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<FinishedTour> FinishedTours { get; set; }
        public virtual DbSet<GuaranteeFeeConfiguration> GuaranteeFeeConfigurations { get; set; }
        public virtual DbSet<IrregularOrder> IrregularOrders { get; set; }
        public virtual DbSet<OrderHistory> OrderHistories { get; set; }
        public virtual DbSet<OrderHistoryDetail> OrderHistoryDetails { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<RegularOrder> RegularOrders { get; set; }
        public virtual DbSet<Revenue> Revenues { get; set; }
        public virtual DbSet<RevenueDetail> RevenueDetails { get; set; }
        public virtual DbSet<Seat> Seats { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketHistory> TicketHistories { get; set; }
        public virtual DbSet<TicketPriceConfiguration> TicketPriceConfigurations { get; set; }
        public virtual DbSet<TicketReturnFeeConfiguration> TicketReturnFeeConfigurations { get; set; }
        public virtual DbSet<TicketSaleDate> TicketSaleDates { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<TransportPriceConfiguration> TransportPriceConfigurations { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
