//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportPriceConfiguration
    {
        public string id { get; set; }
        public string size { get; set; }
        public double weight_from { get; set; }
        public double weight_to { get; set; }
        public decimal transport_price { get; set; }
    }
}
