/**
 * Autogenerated by Thrift Compiler (0.8.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace TransportService
{

  [Serializable]
  public partial class TTransportPrice : TBase
  {
    private string _PriceId;
    private string _Size;
    private double _WeightFrom;
    private double _WeightTo;
    private double _TransportPrice;

    public string PriceId
    {
      get
      {
        return _PriceId;
      }
      set
      {
        __isset.PriceId = true;
        this._PriceId = value;
      }
    }

    public string Size
    {
      get
      {
        return _Size;
      }
      set
      {
        __isset.Size = true;
        this._Size = value;
      }
    }

    public double WeightFrom
    {
      get
      {
        return _WeightFrom;
      }
      set
      {
        __isset.WeightFrom = true;
        this._WeightFrom = value;
      }
    }

    public double WeightTo
    {
      get
      {
        return _WeightTo;
      }
      set
      {
        __isset.WeightTo = true;
        this._WeightTo = value;
      }
    }

    public double TransportPrice
    {
      get
      {
        return _TransportPrice;
      }
      set
      {
        __isset.TransportPrice = true;
        this._TransportPrice = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool PriceId;
      public bool Size;
      public bool WeightFrom;
      public bool WeightTo;
      public bool TransportPrice;
    }

    public TTransportPrice() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              PriceId = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Size = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Double) {
              WeightFrom = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Double) {
              WeightTo = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.Double) {
              TransportPrice = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TTransportPrice");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (PriceId != null && __isset.PriceId) {
        field.Name = "PriceId";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(PriceId);
        oprot.WriteFieldEnd();
      }
      if (Size != null && __isset.Size) {
        field.Name = "Size";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Size);
        oprot.WriteFieldEnd();
      }
      if (__isset.WeightFrom) {
        field.Name = "WeightFrom";
        field.Type = TType.Double;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(WeightFrom);
        oprot.WriteFieldEnd();
      }
      if (__isset.WeightTo) {
        field.Name = "WeightTo";
        field.Type = TType.Double;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(WeightTo);
        oprot.WriteFieldEnd();
      }
      if (__isset.TransportPrice) {
        field.Name = "TransportPrice";
        field.Type = TType.Double;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(TransportPrice);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TTransportPrice(");
      sb.Append("PriceId: ");
      sb.Append(PriceId);
      sb.Append(",Size: ");
      sb.Append(Size);
      sb.Append(",WeightFrom: ");
      sb.Append(WeightFrom);
      sb.Append(",WeightTo: ");
      sb.Append(WeightTo);
      sb.Append(",TransportPrice: ");
      sb.Append(TransportPrice);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
