//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : TransportSystem
//  @ File Name : IOrderBusiness.cs
//  @ Date : 12/17/2013
//  @ Author : khoatd
//
//
using DBManagement;

namespace AppCommon.Business
{
    public interface IOrderBusiness<T> where T : System.Data.Objects.DataClasses.EntityObject
    {
        string ChangeStatus(string id, string deliveryStatus);
        string Insert(T order, System.Collections.ObjectModel.Collection<OrderItem> orderItems);
    }
}
